### ISSUE TITLE
How to view a signed envelope?

### ISSUE THREAD

**Issue by chismo950** [docusign/docusign-esign-node-client#290]
I got envelope data from envelopesApi.getEnvelope, in the response data, I can find for example: "envelopeUri": "/envelopes/bc4799a2-xxxx-xxxx-xxxx-20d1921aeb87" according https://developers.docusign.com/docs/esign-rest-api/how-to/get-envelope-information/
this envelopeUri is a relative path, what is the base URL of it?
and which field in the response data is a signed document?

**Comment by EdwinMoralesDS** [comment]
@chismo950  the base URL for all API calls to the eSignature API uses the following structure:

https://{sub-domain}.docusign.net/restapi/v2.1/accounts/{accountId}

The signed document is not included in the response to the getEnvelope API call. You can use the include parameter to request document information but the document itself will not be included. To get the signed  PDF file you have to use the getEnvelopeDocuments API call instead

Here is the documentation:
https://developers.docusign.com/docs/esign-rest-api/reference/envelopes/envelopedocuments/get/

Here are some code samples for this process: 
https://developers.docusign.com/docs/esign-rest-api/how-to/download-envelope-documents/

Note: If you have multiple documents in your envelope then you can use the 'archive' or 'combined' keywords instead of the documentID to get all of the documents in a single API call

**Comment by chismo950** [comment]
I use envelopesApi.createEnvelope and signed a document, then use this command: 
`curl --request GET "https://demo.docusign.net/restapi/v2.1/accounts/6acecf9a-xxxx-xxxx-xxxx-b8f9a9ec8141/envelopes/bd7633fe-xxxx-xxxx-xxxx-2707653f5167/documents/1" --header "Authorization: Bearer eyJ0exxxx" --output desktop/fila_name.pdf`
to get a pdf file, but this pdf document is still not signed.
What is the right way to get a signed document? envelopeId generated by envelopesApi.createEnvelope is different from the signed envelopeId?

**Comment by chismo950** [comment]
> @chismo950 the base URL for all API calls to the eSignature API uses the following structure:
> 
> https://{sub-domain}.docusign.net/restapi/v2.1/accounts/{accountId}
> 
> The signed document is not included in the response to the getEnvelope API call. You can use the include parameter to request document information but the document itself will not be included. To get the signed PDF file you have to use the getEnvelopeDocuments API call instead
> 
> Here is the documentation: https://developers.docusign.com/docs/esign-rest-api/reference/envelopes/envelopedocuments/get/
> 
> Here are some code samples for this process: https://developers.docusign.com/docs/esign-rest-api/how-to/download-envelope-documents/
> 
> Note: If you have multiple documents in your envelope then you can use the 'archive' or 'combined' keywords instead of the documentID to get all of the documents in a single API call

Solved, thanks~
