### ISSUE TITLE
Text Tabs

### ISSUE THREAD

**Issue by Treepublic-Solar** [docusign/docusign-esign-node-client#368]
Hi everyone,

I’m able to send out envelopes for signature in Node.js via the docusign-esign NPM package, but my text fields are not populating for some reason.  I am referencing [the documentation linked here](https://developers.docusign.com/docs/esign-rest-api/how-to/set-template-tab-values/).  I’ve tried both on our developer account as well as our production account.

Here is my code for creating the envelope.  I am getting the label and ID for the text fields through the Docusign API, and I have double-checked the label is correct through the Docusign webapp itself.
```
function makeEnvelope(args) {
    try {
        let envelope = new docusign.EnvelopeDefinition();
        envelope.templateId = args.templateId;
        let text = docusign.Text.constructFromObject({
            tabLabel: TAB_1_LABEL,
            value: 'test text field!',
        });

        let textExtra = docusign.Text.constructFromObject({
            font: 'helvetica',
            font_size: 'size14',
            tabLabel: TAB_2_LABEL,
            height: '23',
            width: '84',
            required: 'false',
            bold: 'true',
            value: "test value!!!!",
            locked: false,
            tabId: TAB_2_ID
        });

        let tabsFromDocs = docusign.Tabs.constructFromObject({
            textTabs: [text, textExtra]
        });

        let signer1 = docusign.TemplateRole.constructFromObject({
            email: args.signerEmail,
            name: args.signerName,
            roleName: 'signer',
            tabs: tabsFromDocs
        });

        let signer2 = new docusign.TemplateRole();
        signer2.email = args.signer2Email; 
        signer2.name = args.signer2Name;
        signer2.roleName = 'signer';

        envelope.templateRoles = [signer1, signer2];
        envelope.status = 'sent';

        return envelope;
    } catch (error) {
        console.log({ errorMakeEnvelope: error });
    }
}
```
Any help would be much appreciated!!

**Comment by ByungjaeChung** [comment]
It seems like the description of this page (https://developers.docusign.com/docs/esign-rest-api/how-to/set-template-tab-values/) is wrongly documented. This page only shows how you update the value of the regular text tab in the template, not the prefill tab. I filed the Jira DEVDOCS-15231 and the document will be updated.

I've reviewed your code and I assume you are trying to update the value of the prefill tab in the template. If you want to update the value of the prefill tab, you should create the envelope and then edit the prefill tabs to update the value. The sequence of the API calls should be like below:

1. Create an Envelope in a draft status
2. Get document tabs to retrieve the prefill tab Id (https://developers.docusign.com/docs/esign-rest-api/reference/envelopes/envelopedocumenttabs/get/)
3. Update prefill tabs (https://developers.docusign.com/docs/esign-rest-api/reference/envelopes/envelopedocumenttabs/update/)
4. Send envelope

Since this requires much work, I recommend using a regular text tab and making it read-only (lock) so the recipient can't update the tab's value. If you use the regular text tab in the template, you can use the current code.

**Comment by Treepublic-Solar** [comment]
Hi Byungjae, thanks so much for getting back to me!

I am using regular text tabs in the template, as shown below.  I have also double-checked that the text tab ID (which I pulled from the API by getting the document tabs) is correct by referencing the value on the right.
![Image 9-10-24 at 2 47 AM](https://github.com/user-attachments/assets/c4270dad-e6b6-4fc6-81e1-38ba9b2ab36c)

**Comment by Treepublic-Solar** [comment]
This is all set now!  I was using the wrong role name.  I should have used "Signer 1", which I defined for the signer in the Docusign web app.
